### ISSUE TITLE
can't get it to work on version 2

### ISSUE THREAD

**Issue by moovida** [LinusCDE/rmTouchToggler#1]
Hi, I tried to follow your instruction, but I couldn't get it to work. 
Is there a way to figure if I am just pushing the buttons wrong or if it doesn't work on version 2 of the software? Thanks a lot.

**Comment by LinusCDE** [comment]
Hi,
I justed tested it, and it seems to work. Did you copy the service file again after the update?

Otherwise, run the binary manually and check whether the following lines appear when toggling.
```
remarkable: /home/root/ ./touchToggler 
Touchpad grabbed. Not input possible!
Touchpad released. Input possible again.
```

You can also check the logs using `systemctl status touchToggler`. And verify that the service is running there at all.

The old binary should work just fine on 2.0 (tested). 

Edit: Grammar.

**Comment by moovida** [comment]
Thanks for your reply @LinusCDE .
The manual execution does exactly what you describe above.

I apologize, but I might have misunderstood what the application does.  Once pushed left+right buttons together, I should not be able to turn the page to left or right using the buttons. Is that so?

**Comment by LinusCDE** [comment]
> Once pushed left+right buttons together, I should not be able to turn the page to left or right using the buttons. Is that so?

That's right. The program then grabs the touchpad input which means that only that program can receive any events for that device which means that xochitl can't.

Try to re-copy and re-start the .service file. That file is responsible for (automatically) executing the program in background as commanded with systemctl.

**Comment by moovida** [comment]
Ahhh, I now get it. Sorry, I had indeed misunderstood the way of working.
Just to make sure I get it now.

What it does:
* I push together left+right buttons
* **the screen** does only allow input by the pen and not with the fingers

What I thought it would do:
* I push together left+right buttons
* the left and right hardware buttons stop working

My biggest problem is that while writing I push the button with the palm of my hand and always make new pages.

**Comment by LinusCDE** [comment]
I looked into that problem. I had trouble blocking only certain buttons since you usually create a secondary device to emit allowed pressed through. But that isn't possible here if I'm not mistaken.

[This solution](https://github.com/LinusCDE/rmButtonToggler/tree/1.0) is will block all buttons upon pressing LEFT+RIGHT. That includes the home and power buttons. So please read the "important" section regarding this. It should solve your problem.

EDIT: Fix markdown

**Comment by moovida** [comment]
Thanks a ton for this! That is exactly what I was looking for! Heading over to that repo.
